# Generated by Django 6.0.3 on 2026-04-03 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0002_userprofile_phone_number_smsnotification'),
    ]

    operations = []
